### ISSUE TITLE
Уточнение требований к визуализации подписей: даты

### ISSUE THREAD

**Issue by vsenko** [kaarkz/ddcard#2]
Текущие формулировки не однозначно определяют какие именно данные должны быть указаны в качестве:
- даты и времени формирования подписи;
- метки времени;
- времени OCSP ответа.

Это связано с тем, что в ответах TSP и OCSP присутствует несколько полей с временем.

Предлагаю уточнить что в качестве *даты и времени формирования подписи* и *метки времени* следует использовать значение поля `genTime` структуры `TSTInfo`, а в качестве *времени OCSP ответа* следует использовать значение поля `thisUpdate`.

**Comment by vsenko** [comment]
@vturekhanov, если не возражаете, я могу внести соответствующие изменения самостотельно.

**Comment by vturekhanov** [comment]
> @vturekhanov, если не возражаете, я могу внести соответствующие изменения самостотельно.

Не возражаю.
