### ISSUE TITLE
Описание репозитория, README.md и пример

### ISSUE THREAD

**Issue by vsenko** [kaarkz/ddcard#3]
Мне кажется что было бы хорошо:
- добавить описание репозитория
- добавить пример сформированной карточки с синтетическими данными
- в README.md добавить пояснения про содержимое репозитория
- в README.md добавить ссылку на открытую реализацию формирования и разбора карточки https://github.com/sigex-kz/ddc

**Comment by vsenko** [comment]
@vturekhanov, если не возражаете, я могу внести соответствующие изменения самостотельно.

**Comment by vturekhanov** [comment]
> @vturekhanov, если не возражаете, я могу внести соответствующие изменения самостотельно.

Не возражаю.

**Comment by vsenko** [comment]
Готово
