### ISSUE TITLE
Уточнение по поводу формата электронных документов

### ISSUE THREAD

**Issue by vsenko** [kaarkz/ddcard#5]
В #1 я поторопился и состался не на ту часть [Правил документирования](https://adilet.zan.kz/rus/docs/P1800000703), для Карточки лучше подходит:
> 45. Электронные документы на хранение передаются согласно государственному стандарту СТ РК "Управление документацией. Формат файлов электронных документов для долгосрочного хранения. Часть 1. Использование PDF 1.4 (PDF/A-1)". 

В соответствии с этим пунктом единственный подходящий формат для электронных документов долгострочного хранения - PDF.

**Comment by vturekhanov** [comment]
Исправил.
